spring:
  application:
    name: h3-java

  # MySQL
  datasource:
    url: jdbc:mysql://db-k3dlu.pub-cdb.ntruss.com:3306/heeil?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: heeil
    password: heeil@0801
    driver-class-name: com.mysql.cj.jdbc.Driver

  # MongoDB Atlas
  data:
    mongodb:
      uri: mongodb+srv://dev:heeil%400801%21%40%23@cluster0.u0ykepl.mongodb.net/h3?appName=Cluster0&connectTimeoutMS=10000&socketTimeoutMS=30000&serverSelectionTimeoutMS=10000

  # RabbitMQ
  rabbitmq:
    host: 101.101.211.31
    port: 5672
    username: heeilh3
    password: heeil@0801!@#
    virtual-host: heeil.h3

  # Spring Batch 메타 테이블 자동 생성 안 함
  batch:
    jdbc:
      initialize-schema: never

kakao:
  sa:
    client-id: 1bc34ca0c3ea23dbb3e1259e08912e9d
    client-secret: CgtEYS9tWvpaQxCY3ZY1H7JKQYV4EJky
  mo:
    client-id: 1bc34ca0c3ea23dbb3e1259e08912e9d
    client-secret: CgtEYS9tWvpaQxCY3ZY1H7JKQYV4EJky

# MyBatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.h3.h3_java
  configuration:
    map-underscore-to-camel-case: true
